// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference path=".nuxt/nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path=".nuxt/components.d.ts" />
/// <reference path=".nuxt/auto-imports.d.ts" />
export {};
