language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/vue/node_modules

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/packages/vue/node_modules/.cache/babel-loader

jobs:
  include:
    - stage: Precache
      script: yarn install --frozen-lockfile

    - stage: Build
      name: Lint + Test
      script:
        - cd packages/vue
        - yarn lint
        - yarn test:unit

    - stage: Build
      name: Build
      script:
        - cd packages/vue
        - yarn build
