"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.changeFrameworkPathInImports = exports.removeCode = exports.changeImports = exports.extractImports = void 0;
const extractImports = (framework) => new RegExp(`// import ${framework}(.*?)// end import ${framework}`, 'gs');
exports.extractImports = extractImports;
const changeImports = (framework) => new RegExp(`import(.*)from.*../sfui/frameworks/${framework}.*`, 'gm');
exports.changeImports = changeImports;
const removeCode = (framework) => new RegExp(`// ${framework}.*?// end ${framework}`, 'gs');
exports.removeCode = removeCode;
const changeFrameworkPathInImports = (framework) => new RegExp(`(import.*from.*)(/${framework}/)(.*)`, 'gm');
exports.changeFrameworkPathInImports = changeFrameworkPathInImports;
