name: Publish prod version and create sync PR
on:
  push:
    branches:
      - v2

jobs:
  publish-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn --immutable
      - name: Publish Production version
        # run: yarn changeset publish
        run: echo publish package
        env:
          # Needs access to publish to npm
          # refresh token before Saturday, May 25, 2024
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
      - name: Create PR to develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B v2-develop --title 'chore: automatic Sync v2->v2-develop PR' --body 'This Pull Request is generated automatically with changes pushed into `v2` branch. `v2` and `v2-develop` branches should be in-sync.' --label automerge || true
      - name: Merge created PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --merge
