name: Generate changelog on v2-release
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited
  issue_comment:
    types: [created, edited, deleted]

defaults:
  run:
    shell: bash

jobs:
  create-release-changelog:
    name: Create PR with changelog
    runs-on: ubuntu-latest
    # if: ${{ startsWith( github.ref, 'refs/heads/v2-release' ) }}
    steps:
      - run: echo ${{github.ref}}
      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.refs.outputs.head_ref }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
        # Check if there is comment !release
      # - name: Check comments
      #   id: commit_message
      #   run: echo "result=${{ github.event.issue.pull_request && contains(github.event.comment.body, '!release') }}" >> $GITHUB_OUTPUT
      # - name: Find a comment using a search term.
      #   uses: sandeshjangam/comment-actions@v1
      #   id: find_comment
      #   with:
      #     type: 'find'
      #     search_term: '!preview'
      #     number: ${{ github.event.pull_request.number }}
      - name: LOOOG
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: '!release'
          direction: 'last'
      - name: LOG
        run: echo "${{ steps.find_comment.outputs.comment-body }}"
        # by default should be rc changelog
      - name: If comment exists run RC mode (default)
        if: steps.find_comment.outputs.comment-body
        run: yarn changeset pre enter rc
      - name: If comment does not exists run NOT rc mode
        if: steps.find_comment.outputs.comment-body
        run: yarn changeset pre exit
      - name: Create PR with changelog
        id: changesets
        uses: changesets/action@v1
        with:
          commit: '[ci] - release'
          title: '[ci] - release'
        env:
          # Needs access to publish to npm
          # refresh token before Saturday, May 25, 2024
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
