name: Generate changelog on v2-release
on:
  push:
    branches:
      - v2-release/**
  pull_request:
    types:
      - opened
    branches:
      - v2-release/**

jobs:
  create-release-changelog:
    name: Create PR with changelog
    needs: [build, build-release, cypress-react, cypress-vue]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: ConsoleLOG
        run: echo ${{ fromJSON($(cat .changeset/pre.json )).mode }}
      - name: Check if .changeset/pre.json file contain "mode:pre"
        id: prerelease_check
        run: echo "result=$(echo ${{ fromJSON($(cat .changeset/pre.json )).mode == "pre" }})" >> $GITHUB_OUTPUT
      - name: ConsoleLOG2
        run: echo ${{ steps.prerelease_check.output.result }}
      - name: Create PR with changelog
        id: changesets
        uses: changesets/action@v1
        with:
          commit: '[ci] - release${{ steps.prerelease_check.output.result && " rc" }}'
          title: '[ci] - release${{ steps.prerelease_check.output.result && " rc" }}'
        env:
          # Needs access to publish to npm
          # refresh token before Saturday, May 25, 2024
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
