name: Generate changelog on v2-release
on:
  push:
    branches:
      - v2-release/**

jobs:
  create-release-changelog:
    name: Create PR with changelog
    needs: [build, build-release, cypress-react, cypress-vue]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: ConsoleLOG
        ron: echo fromJSON($(cat .changeset/pre.json )).mode
      - name: Set VAR if .changeset/pre.json file contain "mode:pre"
        id: vars
        run: echo "isInPreMode=$(echo ${{ fromJSON($(cat .changeset/pre.json )).mode == "pre" }})" >> $GITHUB_OUTPUT
      - name: Create PR with changelog
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn run changeset-version
          commit: '[ci] - release${{ steps.vars.output.isInPreMode && " rc" }}'
          title: '[ci] - release${{ steps.vars.output.isInPreMode && " rc" }}'
        env:
          # Needs access to publish to npm
          # refresh token before Saturday, May 25, 2024
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
