name: Generate changelog on v2-release
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited
    branches:
      - v2-release/**
  workflow_dispatch:
  issue_comment:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  create-release-changelog:
    name: Create PR with changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
        # Check if there is comment !release
      - name: Check comments
        id: commit_message
        run: echo "result=${{ github.event.issue.pull_request && contains(github.event.comment.body, '!release') }}" >> $GITHUB_OUTPUT
      - name: LOG
        run: echo ${{ steps.commit_message.outputs.result }}
      - name: LOG2
        run: echo ${{ github.event.comment.body }}
        # by default should be rc changelog
      - name: If comment exists run RC mode (default)
        if: steps.commit_message.outputs.result != 'true'
        run: yarn changeset pre enter rc
      - name: If comment does not exists run NOT rc mode
        if: steps.commit_message.outputs.result == 'true'
        run: yarn changeset pre exit
      - name: Create PR with changelog
        id: changesets
        uses: changesets/action@v1
        with:
          commit: '[ci] - release'
          title: '[ci] - release'
        env:
          # Needs access to publish to npm
          # refresh token before Saturday, May 25, 2024
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
