name: ZEIT
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      - name: Build Storybook
        run: |
          yarn
          yarn storybook:build
